---
- name: Prepare OpenStack Ansible deployment package
  hosts: aio1_deploy
  gather_facts: yes
  become: yes
  vars:
    # Release: Train
    # openstack_release: stable/train
    openstack_release: 19.0.5
  tasks:
    - name: Install setup dependencies
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - build-essential
        # - ntp
        # - ntpdate

    - name: Clone openstack-ansible
      git:
        repo: "https://git.openstack.org/openstack/openstack-ansible"
        dest: "/opt/openstack-ansible"
        version: "{{ openstack_release }}"
        update: yes

    - name: Execute script bootstrap-ansible.sh
      shell: scripts/bootstrap-ansible.sh
      args:
        chdir: /opt/openstack-ansible

    - name: Execute script bootstrap-aio.sh
      shell: scripts/bootstrap-aio.sh
      args:
        chdir: /opt/openstack-ansible
      environment:
        SCENARIO: aio_lxc
        BOOTSTRAP_OPTS: bootstrap_host_loopback_cinder=no bootstrap_host_loopback_swift=no bootstrap_host_loopback_nova=no bootstrap_host_ceph=no bootstrap_host_loopback_manila=no

    - name: Copy AIO stop playbook
      copy:
        src: files/stop-aio.yml
        dest: /opt/openstack-ansible/playbooks/

    - name: Copy user variables files
      copy:
        src: files/{{ item }}
        dest: /etc/openstack_deploy/{{ item }}
      with_items:
        - user_variables_ceph.yml
        - user_variables_galera.yml
        - user_variables_neutron.yml

    - name: Ensure debug is set to false
      replace:
        path: /etc/openstack_deploy/user_variables.yml
        regexp: "debug: true$"
        replace: "debug: false"
        backup: no

    - name: Ensure tempest is not installed
      lineinfile:
        path: /etc/openstack_deploy/user_variables.yml
        regexp: "^tempest_install:"
        line: "tempest_install: false"
        backup: no

    - name: Ensure tempest is not run
      lineinfile:
        path: /etc/openstack_deploy/user_variables.yml
        regexp: "^tempest_run:"
        line: "tempest_run: false"
        backup: no

    - name: Replace conf.d files
      copy:
        src: files/conf.d/{{ item }}
        dest: /etc/openstack_deploy/conf.d/{{ item }}
      loop:
        - cinder.yml
        - glance.yml

    - name: Fetch admin password
      shell: cat /etc/openstack_deploy/user_secrets.yml | grep keystone_auth_admin_password
      register: _cmd_admin_pass
      changed_when: false

    - name: Ensure /opt/bin exists
      file:
        path: /opt/bin
        state: directory
        mode: 0755

    - name: Create setup script for OpenStack (/opt/bin/setup_openstack.sh)
      template:
        src: files/bin/setup_openstack.sh.j2
        dest: /opt/bin/setup_openstack.sh
        mode: "u=xrw,g=xr,o=xr"
      vars:
        working_dir: /opt/openstack-ansible/playbooks

    # Not investigated what is remove so that eth0 is down after reboot
    - name: Ensure eth0 will be configured after reboot of machine
      copy:
        content: |
          auto eth0
          iface eth0 inet dhcp
        dest: /etc/network/interfaces.d/eth0.cfg

    - name: Print admin password
      debug:
        var: _cmd_admin_pass.stdout
