---
- name: Basic preparations of target host
  hosts: aio1
  gather_facts: no
  become: yes
  tasks:
    - name: Install Python
      raw: test -e /usr/bin/python || (apt-get update && apt-get -y install python-minimal)
      changed_when: no

    - name: Install aptitude
      raw: test -e /usr/bin/aptitude || (apt-get update && apt-get -y install aptitude)
      changed_when: no

    - name: Apt upgrade all
      apt:
        upgrade: yes
        update_cache: yes

    - name: Removes mitigations for CVE-2017-5715 (aka Spectre / Variant 2) and Meltdown because of CPU hard lockups in kernel 4.4.0-116
      # https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1745349
      lineinfile:
        path: /etc/default/grub
        state: present
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="noibpb nopti"'
      register: _grub_config

    - name: Update GRUB
      shell: update-grub
      when: _grub_config is changed

    - name: Install utils
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - htop

- name: Prepare target host for OpenStack
  hosts: aio1
  gather_facts: no
  become: yes
  tasks:
    - name: Install dependencies
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - bridge-utils
        - debootstrap
        - ifenslave
        - ifenslave-2.6
        - lsof
        - lvm2
        - ntp
        - ntpdate
        - openssh-server
        - sudo
        - tcpdump
        - vlan

- name: Prepare target host for Ceph
  hosts: aio1
  gather_facts: no
  become: yes
  vars:
    data_partition_nr: "{{ data_partition_nr_override | default(2) | int }}"
    os_partition_index: "{{ os_partition_index_override | default((data_partition_nr | int) - 2) | int }}"
  tasks:
    - name: Install dependencies
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - lvm2
        - parted

    - name: Enable and start LVM meta service
      service:
        name: lvm2-lvmetad
        state: started
        enabled: yes

    - name: OS device info (nvme0n1)
      parted:
        device: /dev/nvme0n1
      register: device_info

    - name: Data partition 100% (nvme0n1p{{ data_partition_nr }})
      parted:
        device: /dev/nvme0n1
        number: "{{ data_partition_nr }}"
        flags: [ lvm ]
        state: present
        part_start: "{{ part_start_value }}"
      vars:
        part_start_value: "{{ device_info.partitions[os_partition_index | int].end | int }}KiB"

    - name: Ensure volume group ceph exists
      lvg:
        vg: ceph
        pvs: "/dev/nvme0n1p{{ data_partition_nr }}"
        pesize: 32

    - name: Ensure data volume exists
      lvol:
        vg: ceph
        lv: data
        size: +100%FREE