---
- name: Prepare LVM partitions on target host for Ceph
  hosts: aio1_deploy
  gather_facts: no
  become: yes
  tasks:
    - name: Ensure Ceph LVM partitions are created
      shell: /opt/bin/setup_ceph_lvm.sh
