---
- name: Install Python on target host
  hosts: aio1
  gather_facts: no
  remote_user: ansible
  become: yes  
  tasks:
    - name: Install Python
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal aptitude)
      changed_when: no
    
    - name: Removes mitigations for CVE-2017-5715 (aka Spectre / Variant 2) because of CPU hard lockups in kernel 4.4.0-116
      # https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1745349
      lineinfile:
        path: /etc/default/grub
        state: present
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="noibpb"'
      register: grub_config
    
    - name: Update GRUB
      shell: update-grub
      when: grub_config is changed

- name: Prepare target host for Ceph and OpenStack installation
  hosts: aio1
  gather_facts: no
  remote_user: ansible
  become: yes
  tasks:
    - name: Generate SSH keys
      shell: ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""
      args:
        creates: /root/.ssh/id_rsa

    - name: Get contents of file id_rsa.pub
      command: cat /root/.ssh/id_rsa.pub
      register: id_rsa_pub
      changed_when: no

    - name: Set authorized key for user root to access ansible user
      authorized_key:
        user: ansible
        state: present
        key: "{{id_rsa_pub.stdout}}"
      become: no

    - name: Add Ansible repository
      apt_repository:
        repo: 'ppa:ansible/ansible'
      register: ansible_repo

    - name: Apt upgrade all
      apt:
        upgrade: yes
        update_cache: yes
    
    - name: Install dependencies
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - lvm2
        - software-properties-common
        - parted
        - iptables
        - kpartx
        - ansible

    - name: Enable and start LVM meta service
      service:
        name: lvm2-lvmetad
        state: started
        enabled: yes
