---
- name: Install and configure OpenStack
  hosts: aio1_deploy
  gather_facts: no
  become: yes
  tasks:
    - name: Ensure OpenStack is installed and configured
      shell: /opt/bin/setup_openstack.sh
